# Generated by Django 3.1.2 on 2020-10-22 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Einzelrohr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('anzahl_einzelrohre', models.CharField(choices=[('12', '12'), ('24', '24')], default='24', max_length=2)),
                ('typ', models.CharField(choices=[('Leerrohr', 'Leerrohr'), ('Verbindungsrohr', 'Verbindungsrohr'), ('Verzweigungsrohr', 'Verzweigungsrohr')], default='Verzweigungsrohr', max_length=20)),
                ('einzelrohr_01', models.CharField(max_length=25)),
                ('einzelrohr_02', models.CharField(max_length=25)),
                ('einzelrohr_03', models.CharField(max_length=25)),
                ('einzelrohr_04', models.CharField(max_length=25)),
                ('einzelrohr_05', models.CharField(max_length=25)),
                ('einzelrohr_06', models.CharField(max_length=25)),
                ('einzelrohr_07', models.CharField(max_length=25)),
                ('einzelrohr_08', models.CharField(max_length=25)),
                ('einzelrohr_09', models.CharField(max_length=25)),
                ('einzelrohr_10', models.CharField(max_length=25)),
                ('einzelrohr_11', models.CharField(max_length=25)),
                ('einzelrohr_12', models.CharField(max_length=25)),
                ('einzelrohr_13', models.CharField(blank=True, max_length=25, null=True)),
                ('einzelrohr_14', models.CharField(blank=True, max_length=25, null=True)),
                ('einzelrohr_15', models.CharField(blank=True, max_length=25, null=True)),
                ('einzelrohr_16', models.CharField(blank=True, max_length=25, null=True)),
                ('einzelrohr_17', models.CharField(blank=True, max_length=25, null=True)),
                ('einzelrohr_18', models.CharField(blank=True, max_length=25, null=True)),
                ('einzelrohr_19', models.CharField(blank=True, max_length=25, null=True)),
                ('einzelrohr_20', models.CharField(blank=True, max_length=25, null=True)),
                ('einzelrohr_21', models.CharField(blank=True, max_length=25, null=True)),
                ('einzelrohr_22', models.CharField(blank=True, max_length=25, null=True)),
                ('einzelrohr_23', models.CharField(blank=True, max_length=25, null=True)),
                ('einzelrohr_24', models.CharField(blank=True, max_length=25, null=True)),
                ('reserve_geplant', models.IntegerField(default=0)),
                ('user_created', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('slots', models.IntegerField(default=0)),
                ('linecards', models.IntegerField(default=0)),
                ('linecard_ports', models.IntegerField(default=0)),
                ('ports_max', models.IntegerField(default=0)),
                ('mgmt_cards', models.IntegerField(default=0)),
                ('mgmg_card_position_1', models.IntegerField(default=0)),
                ('mgmg_card_position_2', models.IntegerField(default=0)),
                ('mgmg_card_position_3', models.IntegerField(default=0)),
                ('mgmg_card_position_4', models.IntegerField(default=0)),
                ('user_created', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Kabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('e-Fiber 2x', 'e-Fiber 2x'), ('LTMC', 'LTMC')], default='LTMC', max_length=15)),
                ('buendel_anzahl', models.IntegerField(default=0)),
                ('buendel_groesse', models.IntegerField(default=0)),
                ('faser_anzahl', models.IntegerField(default=0)),
                ('farbe', models.CharField(blank=True, choices=[('Blau', 'Blau'), ('Braun', 'Braun'), ('Cyan', 'Cyan'), ('Gelb', 'Gelb'), ('Grau', 'Grau'), ('Gruen', 'Gruen'), ('Lila', 'Lila'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Rot', 'Rot'), ('Schwarz', 'Schwarz'), ('Weiss', 'Weiss')], default='Rot', max_length=25, null=True)),
                ('lagen', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], default='1', max_length=1, null=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fiberline.customer')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technikstandort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('PoP', 'PoP'), ('MFG', 'MFG')], default='PoP', max_length=10)),
                ('wdm', models.CharField(choices=[('16', '16'), ('32', '32'), ('64', '64'), ('128', '128')], default='64', max_length=10)),
                ('user_created', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fiberline.cluster')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fiberline.customer')),
                ('ies_01', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ies_01', to='app_fiberline.ies')),
                ('ies_02', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ies_02', to='app_fiberline.ies')),
                ('ies_03', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ies_03', to='app_fiberline.ies')),
                ('ies_04', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ies_04', to='app_fiberline.ies')),
                ('ies_05', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ies_05', to='app_fiberline.ies')),
                ('ies_06', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ies_06', to='app_fiberline.ies')),
                ('ies_07', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ies_07', to='app_fiberline.ies')),
                ('ies_08', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ies_08', to='app_fiberline.ies')),
                ('ies_09', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ies_09', to='app_fiberline.ies')),
                ('ies_10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ies_10', to='app_fiberline.ies')),
                ('ies_11', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ies_11', to='app_fiberline.ies')),
                ('ies_12', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ies_12', to='app_fiberline.ies')),
                ('ies_13', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ies_13', to='app_fiberline.ies')),
                ('ies_14', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ies_14', to='app_fiberline.ies')),
                ('ies_15', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ies_15', to='app_fiberline.ies')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fiberline.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Schacht_Kvz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('customer', models.CharField(blank=True, max_length=100, null=True)),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('cluster', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('Kabelverzweiger', 'Kabelverzweiger'), ('Netzverteiler', 'Netzverteiler'), ('Schacht', 'Schacht')], default='Schacht', max_length=25)),
                ('rohr_abgaenge', models.IntegerField(default=3)),
                ('kabel_status_versorgt', models.BooleanField(default=True)),
                ('kabel_b_seite', models.BooleanField(default=False)),
                ('faser_a_versorgt_von', models.IntegerField(default=0)),
                ('faser_a_versorgt_bis', models.IntegerField(default=0)),
                ('faser_b_versorgt_bis', models.IntegerField(default=0)),
                ('geo_latitude', models.CharField(blank=True, default='51.165691', max_length=25, null=True)),
                ('geo_longitude', models.CharField(blank=True, default='10.451526', max_length=25, null=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('kabel_versorgt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_fiberline.kabel')),
                ('rohr_einzelrohre_typ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_fiberline.einzelrohr')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='kabel',
            name='technikstandort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_fiberline.technikstandort'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fiberline.customer'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fiberline.project'),
        ),
    ]
