# Generated by Django 3.1.2 on 2020-10-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fiberline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schacht_kvz',
            name='technikstandort',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schacht_kvz',
            name='technikstandort_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
