# Generated by Django 3.1.2 on 2020-10-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fiberline', '0002_auto_20201022_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='schacht_kvz',
            name='faser_b_versorgt_von',
            field=models.IntegerField(default=0),
        ),
    ]
