# Generated by Django 3.1.2 on 2020-10-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fiberline', '0003_schacht_kvz_faser_b_versorgt_von'),
    ]

    operations = [
        migrations.AddField(
            model_name='schacht_kvz',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schacht_kvz',
            name='user_updated',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
