# Generated by Django 3.1.2 on 2020-10-24 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_fiberline', '0005_auto_20201023_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schacht_kvz',
            name='kabel_a_seite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_site', to='app_fiberline.kabel'),
        ),
        migrations.AlterField(
            model_name='schacht_kvz',
            name='kabel_b_seite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_seite', to='app_fiberline.kabel'),
        ),
    ]
