# Generated by Django 3.1.2 on 2020-10-24 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_fiberline', '0008_auto_20201024_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rohr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('customer', models.CharField(blank=True, max_length=100, null=True)),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('cluster', models.CharField(blank=True, max_length=100, null=True)),
                ('technikstandort_id', models.CharField(blank=True, max_length=255, null=True)),
                ('technikstandort', models.CharField(blank=True, max_length=100, null=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fiberline.einzelrohr')),
            ],
        ),
    ]
