# Generated by Django 3.1.2 on 2020-10-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fiberline', '0009_rohr'),
    ]

    operations = [
        migrations.AddField(
            model_name='rohr',
            name='schacht_kvz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
