# Generated by Django 3.1.2 on 2020-10-24 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_fiberline', '0010_rohr_schacht_kvz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rohr',
            options={'ordering': ['name']},
        ),
    ]
