# Generated by Django 3.1.2 on 2020-10-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fiberline', '0011_auto_20201024_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einzelrohr',
            name='einzelrohr_01',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='einzelrohr',
            name='einzelrohr_02',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='einzelrohr',
            name='einzelrohr_03',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='einzelrohr',
            name='einzelrohr_04',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='einzelrohr',
            name='einzelrohr_05',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='einzelrohr',
            name='einzelrohr_06',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='einzelrohr',
            name='einzelrohr_07',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='einzelrohr',
            name='einzelrohr_08',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='einzelrohr',
            name='einzelrohr_09',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='einzelrohr',
            name='einzelrohr_10',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='einzelrohr',
            name='einzelrohr_11',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='einzelrohr',
            name='einzelrohr_12',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
