# Generated by Django 3.1.2 on 2020-10-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_fiberline', '0012_auto_20201024_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_01',
        ),
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_02',
        ),
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_03',
        ),
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_04',
        ),
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_05',
        ),
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_06',
        ),
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_07',
        ),
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_08',
        ),
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_09',
        ),
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_10',
        ),
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_11',
        ),
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_12',
        ),
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_13',
        ),
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_14',
        ),
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_15',
        ),
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_16',
        ),
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_17',
        ),
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_18',
        ),
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_19',
        ),
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_20',
        ),
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_21',
        ),
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_22',
        ),
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_23',
        ),
        migrations.RemoveField(
            model_name='einzelrohr',
            name='einzelrohr_24',
        ),
    ]
