# Generated by Django 3.1.2 on 2020-10-24 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_fiberline', '0014_auto_20201024_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rohrtyp',
            name='reserve_geplant',
        ),
        migrations.CreateModel(
            name='EinzelrohrTyp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('rohr_typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fiberline.rohrtyp')),
            ],
        ),
    ]
