# Generated by Django 3.1.2 on 2020-10-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fiberline', '0015_auto_20201024_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='einzelrohrtyp',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
