# Generated by Django 3.1.2 on 2020-10-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_fiberline', '0016_einzelrohrtyp_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='einzelrohrtyp',
            options={'ordering': ['rohr_typ', 'number']},
        ),
    ]
