# Generated by Django 3.1.2 on 2020-10-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fiberline', '0018_hausanschlussrohr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hausanschlussrohr',
            name='fiberunit_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
