# Generated by Django 3.1.2 on 2020-10-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fiberline', '0019_auto_20201025_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnikstandortDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=100, null=True)),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('cluster', models.CharField(blank=True, max_length=100, null=True)),
                ('technikstandort_name', models.CharField(max_length=100, unique=True)),
                ('technikstandort_id', models.IntegerField(default=0)),
                ('reserve_verbindungsrohr', models.IntegerField(default=0)),
                ('reserve_verzweigungsrohr', models.IntegerField(default=0)),
                ('fiberunit_04', models.IntegerField(blank=True, null=True)),
                ('fiberunit_08', models.IntegerField(blank=True, null=True)),
                ('fiberunit_12', models.IntegerField(blank=True, null=True)),
                ('fiberunit_24', models.IntegerField(blank=True, null=True)),
                ('user_created', models.CharField(max_length=50)),
                ('user_updated', models.CharField(default='-', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['customer', 'project', 'cluster', 'technikstandort_name'],
            },
        ),
    ]
