# Generated by Django 3.1.2 on 2020-10-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fiberline', '0020_technikstandortdefault'),
    ]

    operations = [
        migrations.AddField(
            model_name='technikstandortdefault',
            name='reserve_tv_zentral_fiber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
