# Generated by Django 3.1.2 on 2020-10-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fiberline', '0021_technikstandortdefault_reserve_tv_zentral_fiber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hausanschlussrohr',
            options={'ordering': ['customer', 'project', 'cluster', 'technikstandort', 'schacht_kvz', 'rohr_typ', 'einzelrohr_number']},
        ),
        migrations.AddField(
            model_name='hausanschlussrohr',
            name='schacht_kvz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
