# Generated by Django 3.1.2 on 2020-10-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fiberline', '0022_auto_20201026_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='hausanschlussrohr',
            name='rohr_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
