# Generated by Django 3.1.2 on 2020-10-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fiberline', '0026_technikstandortdefault_fiberunit_48'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technikstandortdefault',
            name='fiberunit_04',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='technikstandortdefault',
            name='fiberunit_08',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='technikstandortdefault',
            name='fiberunit_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='technikstandortdefault',
            name='fiberunit_24',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='technikstandortdefault',
            name='fiberunit_48',
            field=models.IntegerField(default=0),
        ),
    ]
