# Generated by Django 3.1.2 on 2020-10-29 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_fiberline', '0029_hausanschlussrohr_ort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wohneinheit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('we_number', models.IntegerField(default=1)),
                ('we_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user_created', models.CharField(max_length=50)),
                ('user_updated', models.CharField(default='-', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('hausanschlussrohr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fiberline.hausanschlussrohr')),
            ],
        ),
    ]
